// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var animeReaction = AnimeReaction.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class AnimeReaction
    {
        [JsonProperty("url")]
        public Uri Url { get; set; }
    }

    public partial class AnimeReaction
    {
        public static AnimeReaction FromJson(string json) => JsonConvert.DeserializeObject<AnimeReaction>(json, QuickType.Converter.Settings);
    }
}
