// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var cat = Cat.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Cat
    {
        [JsonProperty("breeds")]
        public object[] Breeds { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("width")]
        public long Width { get; set; }

        [JsonProperty("height")]
        public long Height { get; set; }
    }

    public partial class Cat
    {
        public static Cat[] FromJson(string json) => JsonConvert.DeserializeObject<Cat[]>(json, QuickType.Converter.Settings);
    }
}
